FROM node:20-slim

WORKDIR /app

# Copy package.json & install dependencies
COPY my-app/package*.json ./
RUN npm install

# Copy rest of the code
COPY my-app/. .

# Copy .env.production for API URL
COPY my-app/.env .env


# Expose the dev server port 
EXPOSE 3000

# Start React dev server
CMD ["npm", "start"]
