[servers]
localhost ansible_connection=local
; deployer ansible_host=35.175.149.241 ansible_connection=ssh ansible_user=ubuntu 
; application ansible_host=44.198.191.35 ansible_connection=ssh ansible_user=ubuntu 

uat1 ansible_host=172.19.16.22 ansible_connection=ssh ansible_user=hengly 
gateway ansible_host=172.19.24.47 ansible_connection=ssh ansible_user=hengly 



[all:vars]
ansible_python_interpreter=/usr/bin/python3