---
- name: Nginx
  hosts: server
  become: true
  tasks:
  - name: Update Package
    apt:
      update_cache: yes
  - name: Install Nginx
    apt:
      name: ['nginx']
      state: latest
  - name: Restart Nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
