---
- name: Nginx
  hosts: server
  become: true
  tasks:
  - name: Verify Nginx
    command: systemctl status nginx
    register: result
  - name: Output
    debug:
      msg: '{{ result.stdout_lines }}'
