[local]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

# [db_servers]
# gc-worker01 ansible_host=34.87.108.75 ansible_connection=ssh ansible_user=amhengly db_volume=/home/amhengly/db_data/My-App
# gc-worker02 ansible_host=35.247.133.93 ansible_connection=ssh ansible_user=amhengly db_volume=/home/amhengly/db_data/My-App

# [application]
# gc-worker01 ansible_host=34.87.108.75 ansible_connection=ssh ansible_user=amhengly 
# gc-worker02 ansible_host=35.247.133.93 ansible_connection=ssh ansible_user=amhengly

# [nginx_servers]
# gc-worker01 ansible_host=34.87.108.75 ansible_connection=ssh ansible_user=amhengly
# gc-worker02 ansible_host=35.247.133.93 ansible_connection=ssh ansible_user=amhengly


# [k8s]
# gc-worker01 ansible_host=localhost ansible_connection=ssh ansible_user=root