#SPDX-License-Identifier: MIT-0
---
# tasks file for users

- name: Include SSH user management tasks
  import_tasks: ssh_users/main.yml

- name: Include password user management tasks
  import_tasks: password_users/main.yml 