#SPDX-License-Identifier: MIT-0
---
# tasks file for telegram_notify
 

- name: Send Telegram message
  uri:
    url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
    method: POST
    body_format: json
    body:
      chat_id: "{{ telegram_chat_id }}"
      text: "{{ telegram_msg }}"
    status_code: 200
 