---
- name: Deploy App
  hosts: all
  become: yes

  vars:
    _app_name: "{{ app_name | default('myapp') }}"
    _app_tag: "{{ app_tag | default('latest') }}"
    _git_repo: "{{ git_repo | default('https://github.com/Haihengly/React-App.git') }}"
    _git_branch: "{{ git_branch | default('master') }}"
    _dest_path: "{{ dest_path | default('/app/frontend') }}"
    _host_port: "{{ host_port | default('8089') }}"
    _container_port: "{{ container_port | default('80') }}"

  tasks:

    - name: Pull latest app code from Git
      git:
        repo: "{{ _git_repo }}"
        dest: "{{ _dest_path }}"
        version: "{{ _git_branch }}"
        force: yes

    - name: Build Docker image
      docker_image:
        name: "{{ _app_name }}"
        tag: "{{ _app_tag }}"
        build:
          path: "{{ _dest_path }}"
        source: build
        force_source: yes

    - name: Remove old container
      docker_container:
        name: "{{ _app_name }}"
        state: absent
      ignore_errors: yes

    - name: Start new container
      docker_container:
        name: "{{ _app_name }}"
        image: "{{ _app_name }}:{{ _app_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ _host_port }}:{{ _container_port }}"



          